"""
PRISM Engine — Data source definitions.

Master registry of all Type A (API), Type B (Manual), and Type C (Proxy) sources.
"""

TYPE_A_SOURCES = {
    "A01": {
        "name": "Copernicus CDS ERA5",
        "endpoint": "cds.climate.copernicus.eu/api",
        "auth": "free_token",
        "format": "netcdf",
        "rate_limit": "~100 requests/day",
        "events_served": ["PHY-CLI-*", "PHY-WAT-*"],
        "credential_key": "cds",
    },
    "A02": {
        "name": "USGS ComCat",
        "endpoint": "https://earthquake.usgs.gov/fdsnws/event/1/query",
        "auth": "none",
        "format": "geojson",
        "rate_limit": "unlimited",
        "events_served": ["PHY-GEO-001", "PHY-GEO-004"],
        "credential_key": None,
    },
    "A03": {
        "name": "FRED",
        "endpoint": "https://api.stlouisfed.org/fred/series/observations",
        "auth": "free_key",
        "format": "json",
        "rate_limit": "120 requests/minute",
        "events_served": ["STR-ECO-*", "STR-FIN-*", "OPS-CMP-001"],
        "credential_key": "fred",
    },
    "A04": {
        "name": "NIST NVD",
        "endpoint": "https://services.nvd.nist.gov/rest/json/cves/2.0",
        "auth": "free_key",
        "format": "json",
        "rate_limit": "50 requests/30 seconds (with key)",
        "events_served": ["DIG-CIC-*", "DIG-SCC-*", "DIG-HWS-004"],
        "credential_key": "nvd",
    },
    "A05": {
        "name": "CISA KEV",
        "endpoint": "https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json",
        "auth": "none",
        "format": "json",
        "rate_limit": "unlimited",
        "events_served": ["DIG-CIC-*", "DIG-SCC-*"],
        "credential_key": None,
    },
    "A06": {
        "name": "GPR Index",
        "endpoint": "https://www.matteoiacoviello.com/gpr_files/data_gpr_export.xls",
        "auth": "none",
        "format": "excel",
        "rate_limit": "unlimited",
        "events_served": ["STR-GEO-*"],
        "credential_key": None,
        "alt_url": "https://www.matteoiacoviello.com/gpr_files/data_gpr_daily_recent.xls",
    },
    "A07": {
        "name": "ACLED",
        "endpoint": "https://api.acleddata.com/acled/read",
        "auth": "free_key",
        "format": "json",
        "rate_limit": "500 requests/day",
        "events_served": ["STR-GEO-001", "STR-GEO-004", "STR-GEO-005"],
        "credential_key": "acled_key",
    },
    "A08": {
        "name": "EM-DAT",
        "endpoint": "manual_download",
        "auth": "free_registration",
        "format": "csv",
        "rate_limit": "N/A",
        "events_served": ["PHY-CLI-*", "PHY-GEO-*", "PHY-POL-*"],
        "credential_key": None,
    },
    "A09": {
        "name": "World Bank API",
        "endpoint": "https://api.worldbank.org/v2/",
        "auth": "none",
        "format": "json",
        "rate_limit": "unlimited",
        "events_served": ["STR-ECO-*", "PHY-MAT-*"],
        "credential_key": None,
    },
    "A10": {
        "name": "ENTSO-E",
        "endpoint": "https://transparency.entsoe.eu/api",
        "auth": "free_token",
        "format": "xml",
        "rate_limit": "400 requests/minute",
        "events_served": ["PHY-ENE-*"],
        "credential_key": "entsoe",
    },
    "A12": {
        "name": "UCDP API",
        "endpoint": "https://ucdpapi.pcr.uu.se/api/gedevents/",
        "auth": "none",
        "format": "json",
        "rate_limit": "unlimited",
        "events_served": ["STR-GEO-001", "STR-GEO-005", "STR-GEO-007"],
        "credential_key": None,
    },
    "A13": {
        "name": "NOAA CPC Indices",
        "endpoint": "https://www.cpc.ncep.noaa.gov/data/indices/",
        "auth": "none",
        "format": "text",
        "rate_limit": "unlimited",
        "events_served": ["PHY-CLI-006"],
        "credential_key": None,
    },
}

TYPE_B_SOURCES = {
    "B01": {"name": "Verizon DBIR", "publication_month": 5, "events": ["DIG-RDE-*", "DIG-FSD-*"]},
    "B02": {"name": "FBI IC3", "publication_month": 4, "events": ["DIG-FSD-001", "DIG-FSD-002"]},
    "B03": {"name": "ENISA ETL", "publication_month": 10, "events": ["DIG-SCC-*", "DIG-CIC-*"]},
    "B04": {"name": "Dragos YiR", "publication_month": 2, "events": ["DIG-CIC-002", "DIG-HWS-*"]},
    "B05": {"name": "IRU", "publication_month": 11, "events": ["OPS-RLD-001"]},
    "B06": {"name": "Allianz Trade", "publication_month": 1, "events": ["OPS-SUP-001", "OPS-SUP-006"]},
    "B07": {"name": "Flexera", "publication_month": 2, "events": ["DIG-CLS-*"]},
    "B08": {"name": "WTO TMR", "publication_month": 7, "events": ["STR-TRD-*"]},
    "B09": {"name": "Munich Re NatCat", "publication_month": 1, "events": ["PHY-CLI-*", "PHY-GEO-*"]},
    "B10": {"name": "IATA WATS", "publication_month": 6, "events": ["OPS-AIR-*"]},
    "B11": {"name": "Marsh/WTW", "publication_month": 1, "events": ["STR-GEO-*"]},
}

TYPE_C_PROXIES = {
    "C01": {
        "name": "Semiconductor lead times proxy",
        "proxy_indicator": "Durable goods new orders (computers)",
        "proxy_source": "A03",
        "fred_series": "ACDGNO",
        "calculation": "modifier = current_quarter / rolling_20q_mean",
    },
    "C02": {
        "name": "OT connectivity proxy",
        "proxy_indicator": "ICS-tagged CVE annual count",
        "proxy_source": "A04",
        "nvd_query": "ICS SCADA PLC HMI OT",
        "calculation": "YoY growth rate as attack surface expansion proxy",
    },
    "C03": {
        "name": "Panama Canal water levels proxy",
        "proxy_indicator": "Soil moisture Panama watershed",
        "proxy_source": "A01",
        "cds_variable": "volumetric_soil_water_layer_1",
        "area": {"lat_min": 8, "lat_max": 10, "lon_min": -80, "lon_max": -79},
    },
    "C04": {
        "name": "Blocking pattern frequency proxy",
        "proxy_indicator": "NAO Index (monthly)",
        "proxy_source": "A13",
        "calculation": "Count months with NAO < -1.0 per year",
    },
    "C05": {
        "name": "Semiconductor demand pressure proxy",
        "proxy_indicator": "ISM Manufacturing PMI New Orders",
        "proxy_source": "A03",
        "fred_series": "NAPMNOI",
        "calculation": "modifier = NAPMNOI / 50",
    },
}
